<a href="https://colab.research.google.com/github/TrejosHub/RedesNeuronales/blob/main/Ejercicios_Soluci%C3%B3n_Num%C3%A9rica_de_Ecuaciones_Lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1: Eliminación de Gauss

In [2]:
import numpy as np

# --- Planteamiento 1 ---
A1 = np.array([[2, 3, 1],
               [4, 1, 2],
               [3, 4, 2]], dtype=float)

b1 = np.array([0.5, -1.0, 1.5], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminación de Gauss
sol1 = np.linalg.solve(A1, b1)

# Mostrar la solución
print("Solución del sistema 1:")
print(f"g1 = {sol1[0]:.6f}, g2 = {sol1[1]:.6f}, g3 = {sol1[2]:.6f}")

# --- Planteamiento 2 ---
A2 = np.array([[3, -0.1, -0.2],
               [0.1, 0.7, -0.3],
               [0.3, -0.2, 10]], dtype=float)

b2 = np.array([7.85, -19.3, 71.4], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminación de Gauss
sol2 = np.linalg.solve(A2, b2)

# Mostrar la solución
print("\nSolución del sistema 2:")
print(f"g1 = {sol2[0]:.6f}, g2 = {sol2[1]:.6f}, g3 = {sol2[2]:.6f}")



Solución del sistema 1:
g1 = -1.300000, g2 = 0.400000, g3 = 1.900000

Solución del sistema 2:
g1 = 2.219070, g2 = -25.071871, g3 = 6.571990


Ejercicio 2: Matriz Inversa

In [3]:
import numpy as np

# Matriz de coeficientes A
A = np.array([[3, -0.1, -0.2],
              [0.1, 0.7, -0.3],
              [0.3, -0.2, 10]], dtype=float)

# Vector de términos independientes b
b = np.array([7.85, -19.3, 71.4], dtype=float)

# Calculando la solución usando la matriz inversa
A_inv = np.linalg.inv(A)  # Inversión de la matriz A
sol = np.dot(A_inv, b)  # Multiplicación de A_inv por b

# Mostrar la solución
print("Solución del sistema (pesos ajustados):")
print(f"w1 = {sol[0]:.6f}, w2 = {sol[1]:.6f}, w3 = {sol[2]:.6f}")

Solución del sistema (pesos ajustados):
w1 = 2.219070, w2 = -25.071871, w3 = 6.571990


Ejercicio 3: Método de Jacobi

In [4]:
import numpy as np

def jacobi(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if i != j)
            x_new[i] = (b[i] - s) / A[i, i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    return x

# Matriz de coeficientes
A = np.array([[3, -0.1, -0.2],
              [0.1, 0.7, -0.3],
              [0.3, -0.2, 10]], dtype=float)

# Vector de términos independientes
b = np.array([7.85, -19.3, 71.4], dtype=float)

# Aproximación inicial
x0 = np.zeros_like(b)

# Aplicar el método de Jacobi
sol = jacobi(A, b, x0)

# Mostrar la solución
print("Pesos ajustados usando Jacobi:")
print(sol)

Pesos ajustados usando Jacobi:
[  2.21907032 -25.07187128   6.57199046]


Método de Gauss-Seidel

In [5]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iter

# Matriz de coeficientes
A = np.array([[10, -1, 2],
              [-1, 11, -1],
              [2, -1, 10]], dtype=float)

# Vector de términos independientes
b = np.array([5, 6, 7], dtype=float)

# Valor inicial de las incógnitas
x0 = np.zeros_like(b)

# Resolver el sistema usando el método de Gauss-Seidel
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostrar la solución y el número de iteraciones
print("Solución del sistema:")
print(sol)
print(f"Número de iteraciones: {iteraciones}")



Solución del sistema:
[0.42884615 0.64615385 0.67884615]
Número de iteraciones: 8


Descomposición de Cholesky

In [6]:
from scipy.linalg import cholesky
import numpy as np

# Definir la matriz A y el vector b
A = np.array([[25, 15, -5],
              [15, 18,  0],
              [-5,  0, 11]], dtype=float)

b = np.array([350, 400, 200], dtype=float)

# Verificar que A es simétrica y definida positiva
if np.allclose(A, A.T) and np.all(np.linalg.eigvals(A) > 0):
    # Descomposición de Cholesky
    L = cholesky(A, lower=True)

    # Resolver L * y = b
    y = np.linalg.solve(L, b)

    # Resolver L^T * x = y
    x = np.linalg.solve(L.T, y)

    print("Pesos ajustados usando Cholesky:")
    print(x)
else:
    print("La matriz A no es simétrica o no es definida positiva, Cholesky no es aplicable.")

Pesos ajustados usando Cholesky:
[10.51851852 13.45679012 22.96296296]
